// <auto-generated />
using GeneticsShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeneticsShop.Migrations
{
    [DbContext(typeof(FOXContext))]
    partial class FOXContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeneticsShop.Models.Foxes", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnName("id_product");

                    b.Property<int>("Tails")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tails")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("IdProduct");

                    b.ToTable("Foxes");
                });

            modelBuilder.Entity("GeneticsShop.Models.Katanas", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnName("id_product");

                    b.Property<double>("Sharpness")
                        .HasColumnName("sharpness");

                    b.HasKey("IdProduct");

                    b.ToTable("Katanas");
                });

            modelBuilder.Entity("GeneticsShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(255);

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("price")
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValueSql("((1.0))");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("GeneticsShop.Models.Foxes", b =>
                {
                    b.HasOne("GeneticsShop.Models.Product", "IdProductNavigation")
                        .WithOne("Foxes")
                        .HasForeignKey("GeneticsShop.Models.Foxes", "IdProduct")
                        .HasConstraintName("FK_Foxes_Product");
                });

            modelBuilder.Entity("GeneticsShop.Models.Katanas", b =>
                {
                    b.HasOne("GeneticsShop.Models.Product", "IdProductNavigation")
                        .WithOne("Katanas")
                        .HasForeignKey("GeneticsShop.Models.Katanas", "IdProduct")
                        .HasConstraintName("FK_Katanas_Product");
                });
#pragma warning restore 612, 618
        }
    }
}
